# Generated by Django 5.0.4 on 2024-05-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0003_resumebuilder_address_resumebuilder_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumebuilder',
            name='github',
            field=models.URLField(default='http://www.github.com/default'),
        ),
        migrations.AlterField(
            model_name='resumebuilder',
            name='linkedin',
            field=models.URLField(default='http://www.linkedin.com/default'),
        ),
        migrations.AlterField(
            model_name='resumebuilder',
            name='number',
            field=models.IntegerField(default=1234567890),
        ),
    ]
