# Generated by Django 5.0.4 on 2024-05-21 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0004_alter_resumebuilder_github_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumebuilder',
            name='github',
        ),
    ]
