# Generated by Django 5.0.4 on 2024-05-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0006_alter_resumebuilder_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumebuilder',
            name='github',
            field=models.URLField(default='gihub', null=True),
        ),
    ]
